import { Inter, Lora } from "next/font/google";
import { cookies } from "next/headers";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import "@/styles/main.scss";

export const dynamic = "force-dynamic";

const inter = Inter({ subsets: ["latin"], display: "swap" });
const lora = Lora({ subsets: ["latin"], display: "swap" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const cookieStore = cookies();
  const theme = cookieStore.get("theme")?.value || "light";
  
  return (
    <html
      lang="en"
      className={`${inter.className} ${lora.className} font-sans`}
    >
      <body className={`${inter.className} ${theme === "dark" ? "dark-mode" : ""}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
